# Generated by Django 5.2.17 on 2026-10-01 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profilecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='siren',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='facture',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='facture',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='issuer_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ElectronicInvoiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='superpdp', max_length=30)),
                ('provider_account_id', models.CharField(blank=True, max_length=30)),
                ('connection_status', models.CharField(default='disconnected', max_length=30)),
                ('encrypted_tokens', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, max_length=20)),
                ('company_metadata', models.JSONField(default=dict)),
                ('event_cursor', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_account', to='api.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicInvoiceOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('browser_digest', models.CharField(max_length=64)),
                ('verifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicInvoiceTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='superpdp', max_length=30)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=30)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('submitting', 'Envoi en cours'), ('submitted', 'Déposée'), ('validated', 'Validée'), ('sent', 'Émise'), ('received', 'Reçue'), ('available', 'Mise à disposition'), ('acknowledged', 'Prise en charge'), ('accepted', 'Approuvée'), ('partial', 'Partiellement approuvée'), ('disputed', 'En litige'), ('held', 'Suspendue'), ('completed', 'Complétée'), ('refused', 'Refusée'), ('payment_sent', 'Paiement transmis'), ('payment_received', 'Encaissée'), ('rejected', 'Rejetée'), ('unknown', 'Résultat incertain, réconciliation requise'), ('failed', 'Échec avant transmission')], default='submitting', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('payment_report_status', models.CharField(blank=True, max_length=20)),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.electronicinvoiceaccount')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_transmission', to='api.facture')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicInvoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=30)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electronicinvoiceaccount')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electronicinvoicetransmission')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(default='HUR', max_length=3)),
                ('unit_price_excl_tax', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_excl_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.facture')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='electronicinvoiceaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_account_id', ''), _negated=True), fields=('provider', 'provider_account_id'), name='unique_einvoice_company'),
        ),
        migrations.AddConstraint(
            model_name='electronicinvoiceevent',
            constraint=models.UniqueConstraint(fields=('account', 'provider_event_id'), name='unique_einvoice_event'),
        ),
    ]
