# Generated by Django 5.2.17 on 2026-10-02 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_invoice_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('establishment', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('job', models.CharField(max_length=40)),
                ('custom_job', models.CharField(blank=True, max_length=120)),
                ('dress_code', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cascade', models.BooleanField(default=False)),
                ('rate_kind', models.CharField(default='none', max_length=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='recruiting', max_length=16)),
                ('wave', models.PositiveSmallIntegerField(default=0)),
                ('next_wave_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_reinvited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_requests', to='api.accountprofile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_requests', to='api.accountprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.PositiveSmallIntegerField()),
                ('state', models.CharField(default='queued', max_length=16)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_offers', to='api.accountprofile')),
                ('mission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_offer', to='api.mission')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.missionrequest')),
            ],
            options={
                'ordering': ['wave', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('state', models.CharField(default='submitted', max_length=16)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_timesheet', to='api.facture')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet', to='api.candidateoffer')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=False)),
                ('sound', models.BooleanField(default=True)),
                ('broadcasts', models.BooleanField(default=False)),
                ('jobs', models.JSONField(blank=True, default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='api.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.accountprofile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.candidateoffer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2000, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='api.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_state', models.CharField(default='pending', max_length=16)),
                ('push_state', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.accountprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='notification_event_once')],
            },
        ),
        migrations.AddConstraint(
            model_name='candidateoffer',
            constraint=models.UniqueConstraint(fields=('request', 'extra'), name='one_request_offer_per_extra'),
        ),
    ]
