# Generated by Django 5.2.17 on 2026-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_recruitment_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='missiontimesheet',
            name='original_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
