# Generated by Django 5.2.17 on 2026-10-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_recruitment_billing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='email_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='push_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missiontimesheet',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_timesheet', to='api.facture'),
        ),
    ]
