# Generated by Django 5.2.17 on 2026-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_recruitment_delivery_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='missiontimesheet',
            name='hours',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='missiontimesheet',
            name='original_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
