# Generated by Django 5.2.17 on 2026-10-02 12:50

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_precise_worked_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRequestLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('draft', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_request_link', to='api.accountprofile')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_link', to='api.missionrequest')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.accountprofile')),
            ],
        ),
    ]
