# Generated by Django 5.2.17 on 2026-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='planning_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='default_availability',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='weekly_hours',
            field=models.FloatField(default=35),
        ),
        migrations.AddField(
            model_name='restaurantshift',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurantshift',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantshift',
            name='series_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
