# Generated by Django 5.2.17 on 2026-09-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_restaurant_planning_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantshift',
            name='template_slot_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='RestaurantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('kitchen_end_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('tasks', models.JSONField(default=list)),
                ('template_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='resto.restaurant')),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restaurantshift',
            name='service_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='resto.restaurantservice'),
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('definition', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_templates', to='resto.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantservice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='resto.servicetemplate'),
        ),
        migrations.AddConstraint(
            model_name='restaurantservice',
            constraint=models.UniqueConstraint(fields=('template', 'date'), name='resto_template_date_unique'),
        ),
    ]
