# Generated by Django 5.2.17 on 2026-09-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_group_existing_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmember',
            name='pin_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='restaurantmember',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_sessions', to='resto.restaurantmember')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('normalized', models.CharField(max_length=80)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_catalog', to='resto.restaurant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'normalized'), name='resto_skill_unique')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='resto.servicetemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'date'), name='resto_cancellation_unique')],
            },
        ),
    ]
