# Generated by Django 5.2.17 on 2026-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_seed_recurring_and_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='definition_versions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
